# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details fdfsd
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo
    
    build_after_pull_request:
        steps:
          - checkout
      
    merge_after_pull_request:
        steps:
          - checkout
        
      

workflows:
    version: 2
        - approval_for_build_after_pull_request:
            type: approval
        - build_after_pull_request:
            requires:
                - approval_for_build_after_pull_request
        - approval_for_merge_after_pull_request:
            type: approval
            requires:
                - build_after_pull_request
        - merge_after_pull_request:
            requires:
                - approval_for_merge_after_pull_request
