# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details fdfsd
#
version: 2

references:
## Workspaces
workspace: &workspace
  ~/src


jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

    build_after_pull_request:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
#        working_directory: ~/repo
          
    merge_after_pull_request:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
#        working_directory: ~/repo
            
workflows:
    version: 2
    workflow:
#    deploying_test:
        jobs:
            - build_after_pull_request:
                requires:
                    - approval_for_build_after_pull_request
            - approval_for_build_after_pull_request:
                type: approval
                requires:
                    - build
            - approval_for_merge_after_pull_request:
                type: approval
                requires:
                    - build_after_pull_request
            - merge_after_pull_request:
                requires:
                    - approval_for_merge_after_pull_request
